### PR TITLE
Added Leetcode Problem- Peak Index in Mountain Array

### PR DESCRIPTION
**Pull request by Ruksina01**
Added LeeetCode problem — Peak Index in a Mountain Array
Find the peak index in a mountain array, where elements increase and then decrease.

Approach:
Use binary search:

Complexity:
Time: O(log n)
Space: O(1)

### CODE REVIEW

**Comment by Ruksina01** [comment]
Hey @abhisek247767 
I’ve submitted a pull request, and I would appreciate it if you could review it when you have a moment. Thank you!

**Comment by abhisek247767** [comment]
do in a single file

**Comment by Ruksina01** [comment]
@abhisek247767 
Okay, thanks for letting me know. Can I put that in a Markdown file to enhance the readability in a single file?

**Comment by Ruksina01** [comment]
Hey @abhisek247767 , 
I have sent you a PR, can you check it ?

**Comment by abhisek247767** [comment]
add  problem statement, code and output..no need of readme file. please check other contribution if not understand

**Pull request closed without merging**
