### PR TITLE
Moore's voting algo , q- element that appered more than n/2 time

### PR DESCRIPTION
**Pull request by yashogale30**
**Moore's voting algo**

Question:
Given an array of n integers, find the majority element, 
which is defined as the element that appears more than n/2 times in the array. 
If no such element exists, return -1.

### CODE REVIEW

**Comment by abhisek247767** [comment]
This is time I merged but first create issue then do PR

**Comment by yashogale30** [comment]
Okay , Thank you

**Comment by yashogale30** [comment]
HI @abhisek247767 can you please add hacktoberfest-accepted label to my PR ?
Thank you

**Comment by abhisek247767** [comment]
okay

**Comment by yashogale30** [comment]
Thanks a lot

**Pull request merged**
