### PR TITLE
ADDING PeakIndexMountainArray File

### PR DESCRIPTION
**Pull request by Ruksina01**
Added Leetcode PeakIndexMountainArray 
Approach: Binary Search
Complexity:
— Time: O(log n)
— Space: O(1)

### CODE REVIEW

**Comment by Ruksina01** [comment]
Hey @abhisek247767 ,
I changed it in single file and closed the previous PR

**Comment by abhisek247767** [comment]
ok

**Comment by abhisek247767** [comment]
please do file extension in c++

**Comment by Ruksina01** [comment]
Okay

**Comment by Ruksina01** [comment]
hey @abhisek247767 I changed the file with extension CPP.

**Pull request closed without merging**
