### PR TITLE
 Added Separate Black and White Balls Leetcode Solution

### PR DESCRIPTION
**Pull request by priyamshukla-coder**

### CODE REVIEW

**Comment by abhisek247767** [comment]
issue not found

**Comment by priyamshukla-coder** [comment]
Hi @abhisek247767 

Can you please tell why this is invalid ??

Thanks

**Comment by abhisek247767** [comment]
because you are not created issue

**Comment by priyamshukla-coder** [comment]
Ok so If we want to add any problem as a solution first we need to add the problem statement as a Issue & then contribute to that problem.

**Comment by abhisek247767** [comment]
yes

**Comment by abhisek247767** [comment]
> yes

And it's rule every repository

**Pull request closed without merging**
