### PR TITLE
Adding Leet Code Problems 3 and 234

### PR DESCRIPTION
**Pull request by Ruksina01**
**Longest Substring Without Repeating Characters:**
Problem Statement: Find the length of the longest substring without repeating characters in a given string.
- Complexity:
Time Complexity: O(n)
Space Complexity: O(1)

**Palindrome Linked List**
Problem Statement: Determine if a singly linked list is a palindrome.
- Complexity:
Time Complexity: O(n)
Space Complexity: O(1)

Each solution is implemented in C++ and follows a clear and efficient approach to solve the respective problems.
Proper comments are included for clarity and understanding.

### CODE REVIEW

**Comment by Ruksina01** [comment]
hey @abhisek247767 , can you check my PR for leetcode problems?

**Comment by abhisek247767** [comment]
@Ruksina01 first raised issue then do PR . one things one problem one issue and one PR at a time. I hope you understand

**Comment by Ruksina01** [comment]
@abhisek247767 
I’ll cancel this PR and submit each problem individually.

**Comment by abhisek247767** [comment]
ok

**Pull request closed without merging**
