### PR TITLE
Create creating customhashmap

### PR DESCRIPTION
**Pull request by AbhineetKumar1**
Proposed a solution by creating a hashmap without using hashmap function

### CODE REVIEW

**Comment by AbhineetKumar1** [comment]
this is a hashmap creating code without using hashmap

**Comment by abhisek247767** [comment]
please read the guidelines before do the PR. Please star the repo and follow me for my encouragement

**Comment by AbhineetKumar1** [comment]
I followed you please check and accept my pull request. Please feel free to
ask if any other changes are needed.

**Comment by abhisek247767** [comment]
Done ..I merged. Can you please confirmed is it hacktoberfest included or not?

**Comment by AbhineetKumar1** [comment]
Yes, it worked thanks !

**Pull request merged**
