### PR TITLE
Added solution to Kth largest sum in a Binary tree problem

### PR DESCRIPTION
**Pull request by simran0963**
Added solution to the problem which involves finding kth largest sum of any level in a binary tree, this is a leetcode problem 2583. 
I have provided a c++ solution to the problem.

### CODE REVIEW

**Comment by abhisek247767** [comment]
please push single code file with explanation and code

**Comment by simran0963** [comment]
did the explanation and the combining the two files

**Comment by abhisek247767** [comment]
No. all in single file

**Comment by simran0963** [comment]
The file has the explanation, I have added comments now and everything exists in just one single file.

**Comment by abhisek247767** [comment]
no need of vs code folder. Please check others pR and do conribution.

**Comment by simran0963** [comment]
I have removed the vs code folder now. Hope everything is as required now.

**Pull request merged**
